apiVersion: v1
kind: Service
metadata:
  name: data-tier # nama service
  labels:
    app: microservices
spec:
  ports:
    - port: 6379 # ekspos port redis
      protocol: TCP
      name: redis
  selector:
    tier: data # group untuk pod yang memakai service ini
  type: ClusterIP
--- # memisahkan object service & deployment dalam 1 dokumen manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-tier # nama metada bisa disamakan dengan service (1 aplikasi)
  labels:
    app: microservices
    tier: data # group service data-tier
spec: # spesifikasi container
  replicas: 1
  selector:
    matchLabels:
      tier: data
  template:
    metadata:
      labels:
        app: microservices
        tier: data # container menjadi bagian dari service & deployment
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent # image hanya diunduh bila tidak tersedia secara lokal
          ports:
            - containerPort: 6379
          command:
            - redis-server
            - /etc/redis/redis.conf
          volumeMounts:
            - mountPath: /etc/redis
              name: config
      volumes:
        - name: config
          configMap:
            name: redis-config
            items:
              - key: config
                path: redis.conf
