apiVersion: v1
kind: Pod # mendefinisikan resource yang didefinisikan (Pod)
metadata: # informasi tambahan
  name: mypod
  labels: # selector service. service menemukan pod melalui label (service discovery)
    app: webserver
spec: # tempat menspesifikasikan resource
  containers:
    - name: mycontainer
      image: nginx:latest
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
